site_name: Prefeitura de Palmas 

theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: slate  # modo escuro
    primary: indigo
    accent: deep purple
  

markdown_extensions:
  - smarty
  - toc:
      permalink: true
      separator: "_"
  - sane_lists


+hooks:
   - my_hooks.py

plugins:
  - search
